<resource>
   <id>usrDeliveryPickhopForMultiDrop</id>
   <name>usrDeliveryPickhopForMultiDrop</name>
   <description>Delivery Pickhop Multidrop Setup</description>
   <properties>
	  <property name="stoloc" type="string" description="Location"/>
	  <property name="lngdsc" type="string" description="Movement Zone"/>
   </properties>
   <actions>
      <action type="list" ref="usrListDeliveryPickhopForMultidrop"/>
   </actions>
</resource>
