name: hello-Starware-Squad
'on': workflow_dispatch
jobs:
  GreetingJob:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
         
    steps:
      - name: my-helloWorldGreeting
        run: |
          echo "Hello Starware Squad!"          
          echo 'github.workspace === ${{ github.workspace }}'
          echo "GITHUB_WORKSPACE === $GITHUB_WORKSPACE"
          echo 'runner.workspace === ${{ runner.workspace }}'
          echo "RUNNER_WORKSPACE === $RUNNER_WORKSPACE"
          pwd

  TodayDateJob:
    runs-on: ubuntu-latest
    steps:        
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW # Gives "2022-12-11T01:42:20"  
        
  RunningPerlScriptJob:
    needs: GreetingJob
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Execute Perl script
        run: |
          perl ${{ github.workspace }}/scripts/helloStarware.pl > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: output-log-file
          path: output.log
          
  ReadingPerlResultJob:
    needs: RunningPerlScriptJob
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: output-log-file
      - name: Log Perl script result
        run: |
          value=`cat output.log`
          echo The result is $value
          
  upload-pester-results:
    name: Run Pester and upload results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        shell: pwsh
        run: |
         .\Get-Planet.Tests.ps1 
      - name: Test with Pester
        shell: pwsh
        run: Invoke-Pester Get-Planet.Tests.ps1 -Passthru > pesterOutput.log
      - name: Upload Pester test results
        uses: actions/upload-artifact@v4
        with:
          name: Pester-Test
          path: pesterOutput.log
    if: ${{ always() }}
    
  get-input-file-for-perl-script:
    runs-on: ubuntu-latest
    env: 
     CUSTOMER_NAME: ${{ secrets.CUSTOMER_NAME }}
    steps:
     
     - name: Check out the repository to the runner
       uses: actions/checkout@v4
     - name: Get Input File for Perl Script
       id: modified-list 
       run: |
         echo "modified_files= A db/data/load/base/bootstraponly/poldat/lc_be03_otm_poldat_swiftlex-2715.csv M src/cmdsrc/usrint/send_lc_be03_otm_transport_plan.mcmd" >> $GITHUB_OUTPUT  
         echo "CUSTOMER_NAME : $CUSTOMER_NAME"
     - name: Execute Perl Create Rollout script
       run: |
         perl ${{ github.workspace }}/scripts/createRolloutPackageManual.pl -c $CUSTOMER_NAME -g "${{ steps.modified-list.outputs.modified_files }}" -n RLTEST1 -d rollout -r inputFile.txt -f -l RLTEST1.log -p -o -m
     - name: Check output files
       run: |
         ls ${{ github.workspace }}/rollout/RLTEST1.tar
     - name: Upload tar file
       id: tar-file
       uses: actions/upload-artifact@v4
       with:
          name: output-tar-file
          path: ${{ github.workspace }}/rollout/RLTEST1.tar
         # path: echo "changed_files= ${{ github.workspace }}/rollout/RLTEST1.tar" >> $GITHUB_OUTPUT
   #  - uses: GuillaumeFalourd/copy-push-files@v1
   #    with:
    #      email: ${{ github.actor }}[bot]@users.noreply.github.com
    #      name: ${{ github.actor }}
    #      commit_message: "Create package "
    #      target_branch: ${{ github.head_ref }}
    #      source_files: ${{ github.workspace }}/rollout/RLTEST1.tar
    #      target_dir: ./rollouts/${{ github.head_ref }}
    #      remote_repository: https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }} 
    #      access_token: ${{ github.token }} 
    
    
   
