name: hello-world
'on': workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-helloWorldGreeting
        run: echo "Hello There!"
        
      - uses: actions/checkout@v4

      - name: Change text file
        run: |
          echo "Modified" > new.txt
