name: hello-Starware-Squad
'on': workflow_dispatch
jobs:
  GreetingJob:
    runs-on: ubuntu-latest
    steps:
      - name: my-helloWorldGreeting
        run: |
          echo "Hello Starware Squad!"
          echo 'This is my workspace: ${{ github.workspace }}'
          pwd
          Copy 'Scripts/' '${{ github.workspace }}/Scripts'
          #cd ./scripts
          ls
          #perl ./build_rollout.pl -h
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW # Gives "2022-12-11T01:42:20"
  

       
