name: hello-Starware-Squad
'on': workflow_dispatch
jobs:
  GreetingJob:
    runs-on: ubuntu-latest
    steps:
      - name: my-helloWorldGreeting
        run: |
          echo "Hello Starware Squad!"          
          echo 'github.workspace === ${{ github.workspace }}'
          echo "GITHUB_WORKSPACE === $GITHUB_WORKSPACE"
          echo 'runner.workspace === ${{ runner.workspace }}'
          echo "RUNNER_WORKSPACE === $RUNNER_WORKSPACE"
          pwd

  TodayDateJob:
    runs-on: ubuntu-latest
    steps:        
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW # Gives "2022-12-11T01:42:20"  
        
  RunningPerlScriptJob:
    needs: GreetingJob
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Execute Perl script
        run: |
          perl ${{ github.workspace }}/scripts/helloStarware.pl > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: output-log-file
          path: output.log
          
  ReadingPerlResultJob:
    needs: RunningPerlScriptJob
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: output-log-file
      - name: Log Perl script result
        run: |
          value=`cat output.log`
          echo The result is $value
          

       
