name: hello-Starware-Squad
'on': workflow_dispatch
jobs:
  GreetingJob:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: my-helloWorldGreeting
        run: |
          echo "Hello Starware Squad!"          
          echo 'github.workspace === ${{ github.workspace }}'
          echo "GITHUB_WORKSPACE === $GITHUB_WORKSPACE"
          echo 'runner.workspace === ${{ runner.workspace }}'
          echo "RUNNER_WORKSPACE === $RUNNER_WORKSPACE"
          pwd
          ls ${{ github.workspace }}
          #ls ${{ runner.workspace }}
          perl ./helloStarware.pl -h
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW # Gives "2022-12-11T01:42:20"
   
  

       
