name: run-validation
on: 
 #workflow_dispatch:
 workflow_call:
    inputs:
      customer_name:
        description: 'Customer Name'
        required: true
        type: string
        default: 'RFH' 
        
jobs:
 validate-rollout-files:
    name: Run Powershell script
    runs-on: ubuntu-latest #self-hosted
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Get Customer Var
        id: get_customer-name
        shell: bash
        run: |
          if ${{ vars.CUSTOMER_NAME != '' }}; then
            echo "CUSTOMER_NAME=${{ vars.CUSTOMER_NAME }}"  >> $GITHUB_OUTPUT
          else
            echo "CUSTOMER_NAME=${{ github.events.inputs.customer_name }}"  >> $GITHUB_OUTPUT
          fi
      - name: Print Customer Var
        run: |        
         echo "${{ steps.get_customer-name.outputs.CUSTOMER_NAME }}"


         
      - name: Run Powershell Validation
        id: ps-validation
        shell: pwsh
        run: |
          ./scripts/code_review_base_prototype.ps1 ${{ github.workspace }}/rollout > validation.log
     
      - name: Upload validation file
        uses: actions/upload-artifact@v4
        with:
          name: validation-log-file
          path: validation.log 
      
      - name: Get Final Validation result
        run: |
          value=`cat validation.log`
          echo The result is $value    
     # - name: Get Powershell Validation Results
     #   run:  echo "Pwsh output: ${{ steps.ps-validation.outputs.outputContent }}" 
